# Generated by Django 5.0 on 2023-12-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_photo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
    ]
