# Generated by Django 5.0 on 2024-01-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_alter_photo_experience_alter_photo_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.URLField(),
        ),
    ]
